version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.web
    environment: 
      - PORT=3000
    ports:
      - "3000:3000"
  authserver-db:
    image: mongo:3.6.4
