version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.web
    environment: 
      - PORT=5000
    ports:
      - "5000:5000"
  authserver-db:
    image: mongo:3.6.4
